---
- name: Delete OpenShift Project
  hosts: localhost
  gather_facts: no
  vars:
    project_name: myproject

  tasks:
    - name: Check if project exists
      command: oc get project {{ project_name }}
      register: project_check
      ignore_errors: yes

    - name: Delete project if it exists
      command: oc delete project {{ project_name }}
      when: project_check.rc == 0
