---
- name: Create OpenShift Project with Quotas, Limits, and RoleBindings
  hosts: localhost
  gather_facts: no
  vars:
    project_name: myproject
    quota_cpu: "2"
    quota_mem: "4Gi"
    rbac_kind: User        # Can be User or Group
    rbac_user: developer   # Username or Group name
    rbac_role: edit        # ClusterRole: admin/edit/view
  tasks:
    - name: Create Project (Namespace)
      kubernetes.core.k8s:
        state: present
        kind: Namespace
        name: "{{ project_name }}"

    - name: Apply ResourceQuota
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ResourceQuota
          metadata:
            name: "{{ project_name }}-quota"
            namespace: "{{ project_name }}"
          spec:
            hard:
              cpu: "{{ quota_cpu }}"
              memory: "{{ quota_mem }}"
              pods: "10"

    - name: Apply LimitRange
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: LimitRange
          metadata:
            name: "{{ project_name }}-limits"
            namespace: "{{ project_name }}"
          spec:
            limits:
              - type: Container
                default:
                  cpu: "500m"
                  memory: "256Mi"
                defaultRequest:
                  cpu: "250m"
                  memory: "128Mi"

    - name: Bind role to user/group
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: "{{ project_name }}-rbac"
            namespace: "{{ project_name }}"
          subjects:
            - kind: "{{ rbac_kind }}"   # User or Group
              name: "{{ rbac_user }}"   # developer or group name
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: "{{ rbac_role }}"     # admin/edit/view
            apiGroup: rbac.authorization.k8s.io
