---
- name: Generate Availability Report for Key Kubernetes Services
  hosts: localhost
  gather_facts: no
  vars:
    prometheus_url: "https://prometheus-k8s-openshift-monitoring.apps.prince-cluster.ocp02.demo"
    token: "{{ lookup('pipe', 'oc create token prometheus-k8s -n openshift-monitoring') }}"
    days: 30
    services:
      - apiserver
      - scheduler
      - kube-controller-manager
    report_file: "service_availability_report_{{ lookup('pipe','date +%F') }}.txt"
    email_to: "amrutambakare@gmail.com"
    email_from: "amrutambakare@gmail.com"
    smtp_host: "smtp.example.com"
    smtp_port: 587
    smtp_user: "amrutambakare@gmail.com"
    smtp_password: "cyprgrwwfdtzfrwj"   # Best to store in Ansible Vault!

  tasks:
    - name: Init report file
      copy:
        dest: "{{ report_file }}"
        content: "Service Availability Report (Last {{ days }} days)\n-----------------------------------------------------\n"

    - name: Loop through services and append availability
      shell: |
        curl -k -sG \
          -H "Authorization: Bearer {{ token }}" \
          --data-urlencode "query=(sum(sum_over_time(up{job='{{ item }}'}[{{ days }}d])) / sum(count_over_time(up{job='{{ item }}'}[{{ days }}d]))) * 100" \
          "{{ prometheus_url }}/api/v1/query" | jq -r '.data.result[0].value[1]'
      register: result
      loop: "{{ services }}"
      loop_control:
        loop_var: item

    - name: Write availability result to report
      lineinfile:
        path: "{{ report_file }}"
        line: "{{ item.item }} => {{ item.stdout | default('N/A') }} %"
        insertafter: EOF
      with_items: "{{ result.results }}"

    - name: Show final report path
      debug:
        msg: "✅ Report generated at: {{ report_file }}"

    - name: Send report via email
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_password }}"
        to: "{{ email_to }}"
        from: "{{ email_from }}"
        subject: "Kubernetes Service Availability Report - {{ lookup('pipe','date +%F') }}"
        body: |
          Hello Team,

          Please find attached the availability report for key Kubernetes services over the last {{ days }} days.

          Regards,
          Monitoring Automation
        attach:
          - "{{ report_file }}"
